(this["webpackJsonphw-cad-tools"]=this["webpackJsonphw-cad-tools"]||[]).push([[0],[,,,,,,,,function(e,t,s){e.exports={documentationContentBlock:"DocumentationContentBlock_documentationContentBlock__3QuOq",odd:"DocumentationContentBlock_odd__2FVAc",even:"DocumentationContentBlock_even__-G4MM",commandName:"DocumentationContentBlock_commandName__3QgoD",shortcut:"DocumentationContentBlock_shortcut__pWdUj",input:"DocumentationContentBlock_input__3NlGt",output:"DocumentationContentBlock_output__2tnOZ",useCase:"DocumentationContentBlock_useCase__3QGAJ"}},,function(e,t,s){e.exports={sideNav:"SideNav_sideNav__1ZDpT",sideNav__title:"SideNav_sideNav__title__19Ak4",sideNav__category:"SideNav_sideNav__category__1g87J",link:"SideNav_link__2SzdO"}},,function(e){e.exports=JSON.parse('[{"id":"NMTVw3wHFAA","title":"HW 3D Face","summary":"Draws a flat grouping of four-sided 3D faces by clicking perimeter points","commandName":"hw3dface","lspFileNames":["hw3dface.lsp"],"category":"3D Face Commands","shortcut":"3f"},{"id":"DlCabR1WMDs","title":"HW 3D Face Spiderweb","summary":"Draws a flat grouping of three-sided 3D faces by clicking perimeter points","commandName":"hw3dface_spiderweb","lspFileNames":["hw3dface_spiderweb.lsp"],"category":"3D Face Commands","shortcut":"sd"},{"id":"wrBFOnU1tik","title":"HW Add Nodes","summary":"(For use only in matrix files) Adds middle and exterior nodes on every CAD symbol in a matrix file.","commandName":"hwaddnodes","lspFileNames":["hwaddnodes.lsp"],"category":"Construction Line Commands","shortcut":""},{"id":"PCQkiFdAw3o","title":"HW Bridge Mesh","summary":"Connects two non-adjacent polygon meshes.","commandName":"hwbridgemesh","lspFileNames":["hwbridgemesh,lsp"],"category":"Polygon Mesh Commands","shortcut":"bb"},{"id":"j637HrxWS6g","title":"HW Check Mesh","summary":"Quality-checks the normal facing of 3D faces and polygon meshes.","commandName":"hwcheckmesh","lspFileNames":["hwcheckmesh.lsp"],"category":"Quality Checking Commands","shortcut":"ch"},{"id":"NATsPEB2w1I","title":"HW Combine Mesh","summary":"Combines two adjacent polygon meshes together into one.","commandName":"hwcombinemesh","lspFileNames":["hwcombinemesh.lsp"],"category":"Polygon Mesh Commands","shortcut":"c"},{"id":"hSqyj6HPmNs","title":"HW Cut Mesh","summary":"Separates one polygon mesh into two (along an edge).","commandName":"hwcutmesh","lspFileNames":["hwcutmesh.lsp"],"category":"Polygon Mesh Commands","shortcut":"xx"},{"id":"inxbj09hasY","title":"HW Draw Splines","summary":"Maps splines onto a collection of round or rectangular surface entities (like a lounge chair seat or sofa cushion).","commandName":"hwdrawsplines","lspFileNames":["hwsurfacetopolygonmesh_disc.lsp"],"category":"Construction Line Commands","shortcut":""},{"id":"R-eopwfbxaM","title":"HW Draw Table Top","summary":"Draws a table top (3D faces) onto an existing table edge.","commandName":"hwdrawtabletop","lspFileNames":["hwdrawtabletop.lsp"],"category":"Polygon Mesh Commands","shortcut":""},{"id":"cnb3NC2rSNc","title":"HW Edge","summary":"Hides edges on 3D faces. Specifically, this command quality-checks all targeted 3D faces by hiding the interior edges of adjacent 3D faces (only affects groupings of 3D faces that comprise flat surfaces).","commandName":"hwedge","lspFileNames":["hwedge.lsp"],"category":"Quality Checking Commands","shortcut":""},{"id":"MRfTtyMo3o4","title":"HW Edgesurf","summary":"Creates a polygon mesh based on four input splines (works similarly to AutoCAD\'s native EDGESURF command, only this command allows for a small \'fuzz-factor\' between splines. And this command allow you to edit the surf. tab counts immediately after placing it).","commandName":"hwedgesurf","lspFileNames":["es.lsp"],"category":"Polygon Mesh Commands","shortcut":"es"},{"id":"Bk6Z99F4H_k","title":"HW Join","summary":"Creates a spline from two or more adjacent splines (works similarly to AutoCAD\'s native JOIN command, only this command allows for a small \'fuzz-factor\' between splines. ","commandName":"hwjoin","lspFileNames":["hwjoin.lsp"],"category":"Construction Line Commands","shortcut":"hwj"},{"id":"jPKWWpC1UE8","title":"HW Macro Stretch","summary":"(For use only in matrix files) Simultaneously applies a stretch to many symbols in a matrix file. Useful for instance, when you need to change the depth of many wardrobes (or similar item) in a matrix.","commandName":"hwmacro_stretch","lspFileNames":["hwmacro_stretch.lsp"],"category":"Matrix File Macros","shortcut":""},{"id":"3OrrQJsm4xk","title":"HW Mesh Recast","summary":"Changes the surf. tab count of a polygon mesh. Allows you to smooth rough transitions. This command can be used in with HW Cut Mesh and HW Bridge Mesh to mold your meshes into rounded, organic-shaped designs. Warning: this command fundamentally changes the target mesh in a way that is difficult to undo.","commandName":"hwmeshrecast","lspFileNames":["hwmeshrecast.lsp"],"category":"Polygon Mesh Commands","shortcut":"me"},{"id":"xuU_w495pI8","title":"HW Seam Builder","summary":"Changes the shape of the target mesh to show seam lines. This command can be used in conjunction with HW Define New Seam to create a custom seam shape.","commandName":"hwseambuilder_main","lspFileNames":["hwseambuilder_main","hwseambuilder_defineseam"],"category":"Polygon Mesh Commands","shortcut":"se"},{"id":"x7ICBFMp9Qk","title":"HW Surface to Polygon Mesh: 3-Sided","summary":"Creates a polygon mesh from a three-sided surface entity. ","commandName":"hwsurfacetopolygonmesh_3_sided","lspFileNames":["hwsurfacetopolygonmesh_3_sided.lsp"],"category":"Polygon Mesh Commands","shortcut":""},{"id":"aByISB3KY88","title":"HW Surface to Polygon Mesh: Disc","summary":"Creates a polygon mesh from a collection of ring-shaped, or disc-shaped surface entities. ","commandName":"hwsurfacetopolygonmesh_disc","lspFileNames":["hwsurfacetopolygonmesh_disc.lsp"],"category":"Polygon Mesh Commands","shortcut":""},{"id":"zu_qFTEtWFY","title":"HW Surface to Polygon Mesh: Multiple","summary":"Attempts to create polygon meshes from simple surface entities.","commandName":"hwsurfacetopolygonmesh_multiple","lspFileNames":["hwsurfacetopolygonmesh_multiple.lsp"],"category":"Polygon Mesh Commands","shortcut":""},{"id":"oknToZKv2Zc","title":"HW Swap and Stretch","summary":"(For use only in matrix files) Substitutes a selected collection of polygon meshes / 3D faces for another, and subsequently stretches the size. This command was originally designed to quickly change our \'proud-back\' wardrobes into \'inset-back\'. Note: this command can be modified for other applications. So please make a request if you run into a situation where you have a large matrix and you need to make a small \'swap\' modification on all items in the matrix. Many times these issues can be solved with a script faster (and cheaper) than outsourcing the work to another company. ","commandName":"hwswapandstretch","lspFileNames":["hwswapandstretch.lsp"],"category":"Matrix File Macros","shortcut":""},{"id":"R5uVKHVJ9rE","title":"Setting up your _hwloadall File","summary":"The load file sets specified scripts to load into AutoCAD immediately on start up. This gives you access to these commands via command-line every time you use AutoCAD.","commandName":"","lspFileNames":[""],"category":"Getting Started","shortcut":""},{"id":"hpVAudDeVo0","title":"How to Smooth out a Curve","summary":"Example uses HW Cut Mesh, HW Combine Mesh, HW Half Mesh, HW Bridge Mesh, and HW Mesh Recast to smooth out a rough bump in a seat cushion.","commandName":"","lspFileNames":["hwcutmesh","hwcombinemesh","hwhalfmesh","hwbridgemesh","hwmeshrecast"],"category":"Drafting Tutorials","shortcut":""},{"id":"CAY2wXEumMo","title":"How to Round out a Corner on a Sofa Cushion","summary":"Example uses HW Cut Mesh, HW Combine Mesh, HW Half Mesh, HW Bridge Mesh, and HW Mesh Recast to create the corner on a sofa cushion.","commandName":"","lspFileNames":["hwcutmesh","hwcombinemesh","hwhalfmesh","hwbridgemesh","hwmeshrecast"],"category":"Drafting Tutorials","shortcut":""},{"id":"w4uE2ZPlqaU","title":"Copy, Move, and Mirror","summary":"Example of how to use the Copy, Move and Mirror commands (Native AutoCAD commands)","commandName":"","lspFileNames":[""],"category":"Basic Settings / Workspace Commands","shortcut":""},{"id":"TpsknjnOo0g","title":"Move Command Filters","summary":"Example of how to use filters to lock the x, y, or z axes when moving an object.","commandName":"","lspFileNames":[""],"category":"Basic Settings / Workspace Commands","shortcut":""},{"id":"mHk7GgGc51M","title":"HW Mid","summary":"Toggle the \'mid\' object snap on and off.","commandName":"hwmid","lspFileNames":["hwmid.lsp"],"category":"Basic Settings / Workspace Commands","shortcut":"hwmid"},{"id":"aW0f2tRTGxo","title":"Layer Control","summary":"A summary of commands that make it easier to control which layers are frozen and locked.","summaryListing":[["Shortcut","Command Name","Description"],["hwcolorpalette","HW Color Palette","Creates colorful temp layers."],["laiso","Layer Isolate","Isolates the layers of selected objects (all unselected are frozen)."],["laiso_lock","Layer Isolate - Lock","Isolates the layers of selected objects (all unselected are locked)."],["fz","Freeze","Freezes layer of selected object."],["laaa","Layers - Show All","Thaws, unlocks, and shows all layers."],["la","Layer Options","Brings up the Layer Property Manager."],["lc","Layer Options - Close","Closes the Layer Property Manager."],["hwbl","HW Blue","Creates, thaws, unlocks, and sets current the _temp_blue layer."],["hwgr","HW Green","Creates, thaws, unlocks, and sets current the _temp_green layer."],["hwor","HW Orange","Creates, thaws, unlocks, and sets current the _temp_orange layer."],["hwpu","HW Purple","Creates, thaws, unlocks, and sets current the _temp_purple layer."],["hwre","HW Red","Creates, thaws, unlocks, and sets current the _temp_red layer."],["hwsi","HW Silver","Creates, thaws, unlocks, and sets current the _temp_silver layer."],["hwwh","HW White","Creates, thaws, unlocks, and sets current the _temp_white layer."],["hwye","HW Yellow","Creates, thaws, unlocks, and sets current the _temp_yellow layer."],["hwzz","Zero","Creates, thaws, unlocks, and sets current the 0 layer."],["hwdb","HW Dark Blue","Creates, thaws, unlocks, and sets current the _temp_darkblue layer."],["hwdg","HW Dark Green","Creates, thaws, unlocks, and sets current the _temp_darkgreen layer."],["hwdo","HW Dark Orange","Creates, thaws, unlocks, and sets current the _temp_darkorange layer."],["hwdp","HW Dark Purple","Creates, thaws, unlocks, and sets current the _temp_darkpurple layer."],["hwdy","HW Dark Yellow","Creates, thaws, unlocks, and sets current the _temp_darkyellow layer."],["hwchbl","HW Change Blue","Changes all objects in the current selection to be on the _temp_blue layer."],["hwchgr","HW Change Green","Changes all objects in the current selection to be on the _temp_green layer."],["hwchor","HW Change Orange","Changes all objects in the current selection to be on the _temp_orange layer."],["hwchpu","HW Change Purple","Changes all objects in the current selection to be on the _temp_purple layer."],["hwchre","HW Change Red","Changes all objects in the current selection to be on the _temp_red layer."],["hwchsi","HW Change Silver","Changes all objects in the current selection to be on the _temp_silver layer."],["hwchwh","HW Change White","Changes all objects in the current selection to be on the _temp_white layer."],["hwchye","HW Change Yellow","Changes all objects in the current selection to be on the _temp_yellow layer."],["hwchzz","Change Zero","Changes all objects in the current selection to be on the 0 layer."],["hwchdb","HW Change Dark Blue","Changes all objects in the current selection to be on the _temp_darkblue layer."],["hwchdg","HW Change Dark Green","Changes all objects in the current selection to be on the _temp_darkgreen layer."],["hwchdo","HW Change Dark Orange","Changes all objects in the current selection to be on the _temp_darkorange layer."],["hwchdp","HW Change Dark Purple","Changes all objects in the current selection to be on the _temp_darkpurple layer."],["hwchdy","HW Change Dark Yellow","Changes all objects in the current selection to be on the _temp_darkyellow layer."]],"commandName":"","lspFileNames":["laiso.lsp","hwyellow"],"category":"Basic Settings / Workspace Commands","shortcut":""}]')},function(e,t,s){e.exports={codeSnippet:"ShortcutInstructions_codeSnippet__2pJBa",commandShortcut:"ShortcutInstructions_commandShortcut__3ArGz"}},,,function(e,t,s){e.exports={topnav:"Navbar_topnav__3Af9b",active:"Navbar_active__3BiYV",icon:"Navbar_icon__3fowD",topnav__brand:"Navbar_topnav__brand__1coSY"}},,,function(e){e.exports=JSON.parse('[{"id":"hwzapmesh","name":"HW Zap Mesh","shortcut":"hwzapmesh, za","inputs":["<Point>: a vertex of the mesh facet to be removed.","<Point>: a vertex adjacent to the first picked point. "],"output":"<Polygon Mesh>: a mesh with the selected facet removed. ","commandUseCases":["Sometimes a polygon mesh can afford to lose a few facets without negatively affecting the overall look of the CAD symbol. Reducing a mesh\'s facet count in this way can reduce the overall file size of the symbol. "]},{"id":"hwcombinemesh","name":"HW Combine Mesh","shortcut":"hwcombinemesh, c","inputs":["<Polygon Mesh>: any.","<Polygon Mesh>: must be adjacent to the first one."],"output":"<Polygon Mesh>: a combination of the original two input meshes.","commandUseCases":["Some products look more true-to-life if they are built with a single polygon mesh rather than multiple separate ones. For example, trim around a rectangular table is often best represented with a single mesh rather than being split into a separate mesh for each of the four sides. "]},{"id":"hwbridgemesh","name":"HW Bridge Mesh","shortcut":"hwbridgemesh, bb, bb2, bb4, bb8, bb16","inputs":["<Polygon Mesh>: first mesh.","<Point>: first vertex of the mesh #1.","<Point>: second vertex of the mesh #1 (must be adjacent to the first vertex).","<Point>: third vertex of the mesh #1 (must be adjacent to the second vertex, but not adjacent to the second so as to make an L-shape with the three picks).","<Polygon Mesh>: second mesh.","<Point>: first vertex of the mesh #2.","<Point>: second vertex of the mesh #2 (must be adjacent to the first vertex).","<Point>: third vertex of the mesh #2 (must be adjacent to the second vertex, but not adjacent to the second so as to make an L-shape with the three picks)."],"output":"<Polygon Mesh>: the combination of the two input meshes with a new edge joining the first mesh to the second.","commandUseCases":["Creating table tops: Bridge mesh lets you quickly create a flat table top by joining the first half of a table edge to its other half.","Creating meshes that span long distances."]}]')},function(e,t,s){e.exports={embeddedVideo:"EmbeddedVideo_embeddedVideo__agB2g"}},function(e,t,s){e.exports={codeSnippet:"LoadingInstructions_codeSnippet__3F97l",loadingInstructions:"LoadingInstructions_loadingInstructions__2PhKR"}},,,function(e,t,s){e.exports={footer:"Footer_footer__2NNgL",loadingInstructions:"Footer_loadingInstructions__WegNv",commandShortcut:"Footer_commandShortcut__2RM9R"}},function(e,t,s){e.exports={homeContentBlock:"HomeContentBlock_homeContentBlock__2b-bo"}},function(e,t,s){e.exports={tutorialContentBlock:"TutorialContentBlock_tutorialContentBlock__1YgPV"}},function(e,t,s){e.exports={downloadsContentBlock:"DownloadsContentBlock_downloadsContentBlock__1Os4S"}},function(e){e.exports=JSON.parse('[{"id":"d30698e3a97144703848ffae2f0d354d","title":"HW 3D Face","zipDownload":"https://gist.github.com/bentzen-andy/d30698e3a97144703848ffae2f0d354d/archive/8bec2ad7eaee2af8d22641c3872b2baa046211d0.zip"},{"id":"091c0d76c31f6153a175f9729956d603","title":"HW 3D Face Spiderweb","zipDownload":"https://gist.github.com/bentzen-andy/091c0d76c31f6153a175f9729956d603/archive/912a634199b433207123ab71e65a5e65b3122dee.zip"},{"id":"56c6d9c957ec173687a1adaf03acde7d","title":"HW Check Mesh","zipDownload":"https://gist.github.com/bentzen-andy/56c6d9c957ec173687a1adaf03acde7d/archive/11b77785db43cfb1d3590f4a2e5260f7922958a3.zip"},{"id":"fa75afdb8de4e593faf4094d4e4970f7","title":"HW Combine Mesh","zipDownload":"https://gist.github.com/bentzen-andy/fa75afdb8de4e593faf4094d4e4970f7/archive/0a74aaefebe38ab8b46255b7b2dc364f572c2ae3.zip"},{"id":"9aff9fc2345abfecee509c442a863986","title":"HW Cut Mesh","zipDownload":"https://gist.github.com/bentzen-andy/9aff9fc2345abfecee509c442a863986/archive/cfd174248367dc8c8057937bc993b26e38a0f14b.zip"}]')},function(e,t,s){e.exports={error404:"Error404_error404__-47PB"}},function(e,t,s){e.exports={videoSummary:"TutorialSummary_videoSummary__Ks9zn"}},,,,,function(e,t,s){},function(e,t,s){},,,,,,,,,,,function(e,t,s){"use strict";s.r(t);s(1);var o=s(22),a=s.n(o),n=(s(35),s(36),s(37),s(16),s(4)),c=s(0);s(24);var i=s(2),r=s(25),l=s.n(r);function d(){return Object(c.jsxs)("div",{className:l.a.homeContentBlock,children:[Object(c.jsx)("h1",{children:"Getting Started"}),Object(c.jsxs)("p",{children:["Check out the ",Object(c.jsx)(n.b,{to:"/hw-cad-tools/tutorials",children:"tutorial videos"})," ","for step-by-step instructions for each custom command."]})]})}var h=s(26),m=s.n(h),u=s(12),p=s(10),b=s.n(p);function j(e){var t=e.sideNavTitle,s=e.links;return s.sort((function(e,t){return e.title<t.title?-1:e.title>t.title?1:0})),s.sort((function(e,t){return e.category<t.category?-1:e.category>t.category?1:0})),Object(c.jsx)("div",{className:b.a.sideNav,children:Object(c.jsxs)("div",{className:b.a.container,children:[Object(c.jsx)("div",{className:b.a.sideNav__title,children:t}),s.map((function(e,o){return Object(c.jsxs)("section",{children:[0===o&&Object(c.jsx)("div",{className:b.a.sideNav__category,children:e.category}),o>0&&s[o].category!==s[o-1].category&&Object(c.jsx)("div",{className:b.a.sideNav__category,children:e.category}),Object(c.jsx)(n.b,{className:b.a.link,to:"/hw-cad-tools/".concat(t.toLowerCase(),"/").concat((a=e.title,a.toLowerCase().replace(/ /g,"-"))),children:e.title})]},e.id);var a}))]})})}function g(){return Object(c.jsx)("div",{className:m.a.tutorialContentBlock,children:Object(c.jsxs)("div",{className:"row",children:[Object(c.jsx)("div",{className:"column",children:Object(c.jsx)(j,{sideNavTitle:"Tutorials",links:u})}),Object(c.jsxs)("div",{className:"column",children:[Object(c.jsx)("h1",{children:"Video Tutorials"}),Object(c.jsxs)("p",{children:["Click on any of the custom commands in the side-bar to get started."," "]})]})]})})}var f=s(27),y=s.n(f),w=s(28);function x(){return Object(c.jsx)("div",{className:y.a.downloadsContentBlock,children:Object(c.jsxs)("div",{className:"row",children:[Object(c.jsx)("div",{className:"column",children:Object(c.jsx)(j,{sideNavTitle:"Downloads",links:w})}),Object(c.jsxs)("div",{className:"column",children:[Object(c.jsx)("h1",{children:"Custom Commands"}),Object(c.jsxs)("p",{children:["AutoLisp is a scripting language used to write macros and custom commands for AutoCAD. You can view and download any of these custom commands by selecting one from the side-bar menu and clicking the Download button."," "]})]})]})})}var _=s(8),C=s.n(_),O=s(19),v=s(49);O.sort((function(e,t){return e.name<t.name?-1:e.name>t.name?1:0}));var N=O.map((function(e,t){return Object(c.jsxs)("tr",{className:t%2===0?C.a.odd:C.a.even,children:[Object(c.jsx)("td",{children:e.name},Object(v.a)().toString()),Object(c.jsx)("td",{children:e.shortcut},Object(v.a)().toString()),Object(c.jsx)("td",{children:e.inputs.map((function(e){return Object(c.jsx)("div",{children:e},e)}))},Object(v.a)().toString()),Object(c.jsx)("td",{children:e.output},Object(v.a)().toString()),Object(c.jsx)("td",{children:e.commandUseCases.map((function(e){return Object(c.jsx)("div",{children:e},e)}))})]},e.id)}));function k(){return Object(c.jsxs)("div",{className:C.a.documentationContentBlock,children:[Object(c.jsx)("h1",{children:"Documentation"}),Object(c.jsxs)("table",{children:[Object(c.jsx)("thead",{children:Object(c.jsxs)("tr",{children:[Object(c.jsx)("th",{className:C.a.commandName,children:"Command Name"}),Object(c.jsx)("th",{className:C.a.shortcut,children:"Shortcut"}),Object(c.jsx)("th",{className:C.a.input,children:"Input(s)"}),Object(c.jsx)("th",{className:C.a.output,children:"Output / Result"}),Object(c.jsx)("th",{className:C.a.commandUseCases,children:"Use Case(s)"})]})}),Object(c.jsx)("tbody",{children:N})]})]})}var W=s(29),H=s.n(W);function S(){return Object(c.jsx)("div",{className:H.a.error404,children:Object(c.jsxs)("h3",{children:["404 Error: Cannot find page for URL: ",window.location.href]})})}var M=s(20),D=s.n(M),F=function(e){return["the","and","but","aboard","about","above","across","after","against","along","amid","among","around","as","at","before","behind","below","beneath","beside","between","beyond","but","by","concerning","considering","despite","down","during","except","following","for","from","in","inside","into","like","minus","near","next","of","off","on","onto","opposite","out","outside","over","past","per","plus","regarding","since","than","through","till","to","toward","under","underneath","unlike","until","up","upon","versus","via","with","within","without"].includes(e)},B=function(){var e,t=window.location.href.split("/").pop().split("-").join(" ");return t=(t=(e=t,e.split(" ").map((function(e){return e.length<=2||F(e)?e:e.replace(e[0],e[0].toUpperCase())})).join(" ")).replace(/3d/g,"3D")).replace(/hw /g,"HW ")};function P(e){var t=e.url,s=e.width,o=e.height,a=e.showTitle;return Object(c.jsx)("div",{className:D.a.embeddedVideo,children:Object(c.jsxs)("div",{className:D.a.container,children:[Object(c.jsx)("iframe",{width:s,height:o,src:t,title:"YouTube video player",frameBorder:"0",allow:"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture;",allowFullScreen:!0}),Object(c.jsx)("h1",{children:a&&B()})]})})}var z=s(30),A=s.n(z);function T(e){var t=e.video;return Object(c.jsxs)("div",{className:A.a.videoSummary,children:[Object(c.jsx)("p",{children:t.summary&&t.summary}),t.summaryListing&&Object(c.jsxs)("table",{children:[Object(c.jsx)("thead",{children:Object(c.jsxs)("tr",{children:[Object(c.jsx)("th",{children:t.summaryListing[0][0]}),Object(c.jsx)("th",{children:t.summaryListing[0][1]}),Object(c.jsx)("th",{children:t.summaryListing[0][2]})]})}),Object(c.jsx)("tbody",{children:t.summaryListing.slice(1).map((function(e){return Object(c.jsxs)("tr",{children:[Object(c.jsx)("td",{children:Object(c.jsx)("code",{children:e[0]})}),Object(c.jsx)("td",{children:e[1]}),Object(c.jsx)("td",{children:e[2]})]},e[0])}))})]})]})}var L=s(21),I=s.n(L);function R(e){var t=e.video;return""===t.lspFileNames[0]?null:Object(c.jsxs)("div",{className:I.a.loadingInstructions,children:[Object(c.jsx)("h3",{children:"Loading Instructions"}),Object(c.jsxs)("p",{children:["If you'd like to use the command(s) shown in this video, add the following code to your ",Object(c.jsx)("code",{children:"_hwloadall.lsp"})," file (excluding the",Object(c.jsx)("code",{children:"..."}),"):"]}),Object(c.jsxs)("div",{className:I.a.codeSnippet,children:[Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:";; HW Commands"})}),Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:"..."})}),t.lspFileNames.map((function(e){return Object(c.jsx)("div",{children:Object(c.jsxs)("code",{children:["(load C:/kenf/lisp/",e,")"]})},e)})),Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:"..."})})]}),Object(c.jsxs)("p",{children:["Or see the"," ",Object(c.jsx)(n.b,{to:"/hw-cad-tools/tutorials/setting-up-your-_hwloadall-file",children:"instructions"})," ","for setting up your ",Object(c.jsx)("code",{children:"_hwloadall.lsp"})," file."]})]})}var E=s(13),U=s.n(E);function G(e){var t=e.video;return""===t.shortcut?null:Object(c.jsxs)("div",{className:U.a.commandShortcut,children:[Object(c.jsx)("h3",{children:"Command Shortcut:"}),Object(c.jsxs)("p",{children:["If you'd like to set a shortcut for this command, add the following code to your ",Object(c.jsx)("code",{children:"_hwloadall.lsp"})," file (following the load statement):"]}),Object(c.jsxs)("div",{className:U.a.codeSnippet,children:[Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:"..."})}),Object(c.jsxs)("div",{children:[t.lspFileNames.map((function(e){return Object(c.jsx)("div",{children:Object(c.jsxs)("code",{children:["(load C:/kenf/lisp/",e,")"]})},e)}))," ",Object(c.jsxs)("code",{children:["(defun c:",t.shortcut,"( / ) c:",t.commandName,")"]})]}),Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:"..."})})]}),Object(c.jsxs)("p",{children:["OR: You can customize your keyboard shortcut but substituting"," ",Object(c.jsx)("code",{children:"xyz"})," in place of the ",Object(c.jsx)("code",{children:t.shortcut}),", where"," ",Object(c.jsx)("code",{children:"xyz"})," is your shortcut name."]}),Object(c.jsxs)("div",{className:U.a.codeSnippet,children:[Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:"..."})}),Object(c.jsx)("div",{children:Object(c.jsxs)("code",{children:["(defun c:xyz( / ) c:",t.commandName,")"]})}),Object(c.jsx)("div",{children:Object(c.jsx)("code",{children:"..."})})]})]})}var Y=u.map((function(e){return Object(c.jsx)(i.a,{path:"/hw-cad-tools/tutorials/".concat((t=e.title,t.toLowerCase().replace(/ /g,"-"))),exact:!0,children:Object(c.jsxs)("div",{className:"row",children:[Object(c.jsx)("div",{className:"column",children:Object(c.jsx)(j,{sideNavTitle:"Tutorials",links:u})}),Object(c.jsxs)("div",{className:"column",children:[Object(c.jsx)(P,{url:"https://www.youtube.com/embed/".concat(e.id),width:"840",height:"470",showTitle:!0}),Object(c.jsx)(T,{video:e}),Object(c.jsx)(R,{video:e}),Object(c.jsx)(G,{video:e})]})]})},e.id);var t}));function V(){return Object(c.jsx)(c.Fragment,{children:Object(c.jsxs)(i.c,{children:[Object(c.jsx)(i.a,{path:"/hw-cad-tools/",exact:!0,children:Object(c.jsx)(d,{})}),Object(c.jsx)(i.a,{path:"/hw-cad-tools/tutorials",exact:!0,children:Object(c.jsx)(g,{})}),Y,Object(c.jsx)(i.a,{path:"/hw-cad-tools/downloads",exact:!0,children:Object(c.jsx)(x,{})}),Object(c.jsx)(i.a,{path:"/hw-cad-tools/docs",exact:!0,children:Object(c.jsx)(k,{})}),Object(c.jsx)(i.a,{path:"*",children:Object(c.jsx)(S,{})})]})})}var J=function(){return console.log("testing...."),Object(c.jsx)("div",{className:"App",children:Object(c.jsx)(V,{})})},q=function(e){e&&e instanceof Function&&s.e(3).then(s.bind(null,50)).then((function(t){var s=t.getCLS,o=t.getFID,a=t.getFCP,n=t.getLCP,c=t.getTTFB;s(e),o(e),a(e),n(e),c(e)}))};a.a.render(Object(c.jsx)(n.a,{children:Object(c.jsx)(J,{})}),document.getElementById("root")),q()}],[[47,1,2]]]);
//# sourceMappingURL=main.4a695cf2.chunk.js.map